CREATE TABLE PDF (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME           TEXT    NOT NULL,
  HASH           TEXT    NOT NULL,
  DATE           INT     NOT NULL
);

CREATE TABLE WORD (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  WORD           TEXT    NOT NULL,
  TOTAL_COUNT    INT     DEFAULT 0
);

CREATE TABLE FREQ (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PDF_ID         INT     NOT NULL,
  WORD_ID        INT     NOT NULL,
  FREQ_COUNT     INT     NOT NULL
);
